### ISSUE TITLE
Optimze the datasets from Task 2

### ISSUE THREAD

**Issue by PatrykGadziomski** [PatrykGadziomski/Introducion-to-Data-Science-Repo#27]
mnth is not normal distributed (use plots with time values and cnt)

-> atemp; temp multicorrelation

-> instant is relevant

**Comment by TrisRuhm** [comment]
instant included -> better outcome at R^2

tried to transform mnth into normal distribution; didnt worked

not clear what to do with atemp/temp

**Comment by PatrykGadziomski** [comment]
1. nice
2. hmm ok.
3. Because this features are colinear, we only need one of them. So drop temp or atemp

**Comment by AlienAscension** [comment]
1. Instant included gives R^2 Value of above 0.9 which sounds too good to be true. needs further checking
2. if you put train and test data together mnth is normal distributed, no further transformaion required
3. dropped atemp, because we get marginally better results with temp

A couple further Visualisations and exploration concludes, that we have stronger months in relation to cnt:



![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/148532831/8f11e734-1f56-4087-a0bf-f7270fcd3953)

Also we have growth over the years, see this chart were we plot count by instant. In year 2 we have an average growth of 60%



![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/148532831/298f1275-5fa5-4d5e-b4df-941de7ae20db)

Im not sure we can use this info to further improve the model, i thought about calculating an average growth value by month, but that would be a new feature, etc
