### ISSUE TITLE
Evaluate new linear regression model with MAE and R²

### ISSUE THREAD

**Issue by PatrykGadziomski** [PatrykGadziomski/Introducion-to-Data-Science-Repo#29]

**Comment by AlienAscension** [comment]
After the changes from the Optimization (Removing temp mainly) and the corresponding changes of our models. we got following results:



![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/148532831/f7e81a2c-d69f-4c08-8399-0bc3870718c5)

The changes are not signifcant, but better than before.

Since the old Models A, B and C all used temp & atemp the changes were as follows:

Old Model:



![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/148532831/86477dbc-2cab-494c-86ee-3de4bab880d6)

New Model:




![Image](https://github.com/PatrykGadziomski/Introducion-to-Data-Science-Repo/assets/148532831/a99fc05b-2a53-44b3-b592-376b6b64a757)




Overall I expected much better results, especially with the multicollineary temp & atemp removed. The Feature Instant also had no impact.
